logging_enabled: false
logging_level: "WARN"
logging_url: "https://stats.altheamesh.com:9999/compressed_sink/"
source_dir: build
disable_password_login: false
remote_mesh_access: false
insert_keys: false
keys_to_insert:
  - ""
dropbear_wan_accessible: false
ssh_port: 22
password_auth: 0
default_price: 100
wireless_conf_path: "{{role_path}}/templates/{{conf_to_build}}-wireless.j2"

mesh_subnets:
  - "f000::/4" # locally routable address and link local addresses, link local isn't forwarded anyways
  - "2000::/4" # most assigned unicast addresses
  - "3000::/4" # some depricated stuff
  - "4000::/4" # some depricated stuff
  - "5000::/4" # some depricated stuff

wifi_key: "ChangeMe"

lan_ip: "192.168.10.1"
pbs_ip: "192.168.30.1"

wifi_encryption: psk2+tkip+aes

hardcoded_interfaces:
  - "mesh"

listen_interfaces_extended: "{{listen_interfaces + hardcoded_interfaces}}"
